version: '1'

services:
  Exchange:
    image: python_django-exchange
    working_dir: /Exchange
    volumes:
      - ./:/Exchange
    environment:
      'ENGINE': django.db.backends.postgresql
      'NAME': test
      'USER': postgres
      'PASSWORD': amir
      'HOST': postgres
      'PORT': 5432
    ports:
      - 8000:8000
    networks:
      exchangeNet:
        aliases:
          - exchange
#    command:
#      bash -c "python manage.py migrate && python manage.py createcachetable"

  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      'POSTGRES_USER': postgres
      'POSTGRES_PASSWORD': amir
    networks:
      exchangeNet:
        aliases:
          - postgres
  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      exchangeNet:
        aliases:
          - nginx
networks:
  exchangeNet:
    driver: bridge
volumes:
  postgres: