# Generated by Django 4.1.7 on 2023-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('final_price', models.CharField(blank=True, max_length=150, null=True)),
                ('volume', models.CharField(blank=True, max_length=150, null=True)),
                ('price', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
