# Generated by Django 4.1.7 on 2023-03-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asymbol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='stored_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
