# Generated by Django 4.1.7 on 2023-03-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asymbol', '0002_symbol_stored_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='market',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='sector',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='symbol_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='symbol',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='final_price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='price',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='volume',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
