# Generated by Django 4.1.7 on 2023-03-17 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asymbol', '0005_rename_final_price_symbol_final_price_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_name', models.CharField(blank=True, max_length=30, null=True)),
                ('value', models.CharField(blank=True, max_length=30, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
