# Generated by Django 4.1.7 on 2023-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asymbol', '0006_slope'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='is_calculated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
