# Generated by Django 4.1.7 on 2023-04-01 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asymbol', '0007_symbol_is_calculated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='is_calculated',
        ),
    ]
