# Generated by Django 4.1.7 on 2023-04-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asymbol', '0008_remove_symbol_is_calculated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slope',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
